#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

# Exit on command errors and treat unset variables as an error
set -eu

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

if [ ! -e .fonctions ]; then
	# Rapatrie le fichier de fonctions si il n'est pas dans le dossier courant
	sudo cp ../settings/scripts/.fonctions ./.fonctions
	sudo chmod a+rx .fonctions
fi
source .fonctions
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get $app final_path)
domain=$(ynh_app_setting_get $app domain)
appname=$(ynh_app_setting_get $app appname)
sql=$(ynh_app_setting_get $app sql)

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP OF THE MAIN DIR OF THE APP
#=================================================

CHECK_SIZE "$final_path"
ynh_backup "$final_path" "sources"

#=================================================
# BACKUP OF THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$appname.conf" "nginx.conf"

#=================================================
# BACKUP OF THE PHP-FPM CONFIGURATION
#=================================================

ynh_backup "/etc/php5/fpm/pool.d/$appname.conf" "php-fpm.conf"
ynh_backup "/etc/php5/fpm/conf.d/20-$appname.ini" "php-fpm.ini"

#=================================================
# BACKUP OF THE SQL BDD
#=================================================

if [ $sql -eq 1 ];
then
	db_name=$(ynh_app_setting_get $app db_name)
	db_pwd=$(ynh_app_setting_get $app mysqlpwd)
	ynh_mysql_dump_db "$db_name" > dump.sql
	CHECK_SIZE "dump.sql"
	ynh_backup "dump.sql" "db.sql"
fi
