#!/bin/bash

# Récupère les infos de l'application.
webapp=multi_webapp
final_path=$(sudo yunohost app setting $webapp final_path)
domain=$(sudo yunohost app setting $webapp domain)
app=$(sudo yunohost app setting $webapp app)


# The parameter $1 is the backup directory location
# which will be compressed afterward
backup_dir=$1/apps/$webapp
sudo mkdir -p "$backup_dir"

# Backup sources & data
sudo cp -a $final_path/. $backup_dir/sources

# Copy Nginx and YunoHost parameters to make the script "standalone"
sudo cp -a /etc/yunohost/apps/$webapp/. $backup_dir/yunohost
sudo cp -a /etc/nginx/conf.d/$domain.d/$app.conf $backup_dir/nginx.conf

# Copy dedicated php-fpm process to backup folder
sudo cp -a /etc/php5/fpm/pool.d/$app.conf $backup_dir/php-fpm.conf
sudo cp -a /etc/php5/fpm/conf.d/20-$app.ini $backup_dir/php-fpm.ini
