#!/bin/bash

# Récupère les infos de l'application.
ynh_version=$(sudo yunohost -v | grep "moulinette:" | cut -d' ' -f2 | cut -d'.' -f1,2)	# Récupère le numéro de version de Yunohost.
app=$YNH_APP_INSTANCE_NAME

final_path=$(sudo yunohost app setting $app final_path)
domain=$(sudo yunohost app setting $app domain)
appname=$(sudo yunohost app setting $app appname)

# The parameter $1 is the backup directory location
# which will be compressed afterward
backup_dir=$1/apps/$app
sudo mkdir -p "$backup_dir"

# Backup sources & data
sudo cp -a $final_path/. $backup_dir/sources

# Copy Nginx and YunoHost parameters to make the script "standalone"
sudo cp -a /etc/yunohost/apps/$app/. $backup_dir/yunohost
sudo cp -a /etc/nginx/conf.d/$domain.d/$appname.conf $backup_dir/nginx.conf

# Copy dedicated php-fpm process to backup folder
sudo cp -a /etc/php5/fpm/pool.d/$appname.conf $backup_dir/php-fpm.conf
sudo cp -a /etc/php5/fpm/conf.d/20-$appname.ini $backup_dir/php-fpm.ini
