#!/bin/bash

source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script

# Récupère les infos de l'application.
app=$YNH_APP_INSTANCE_NAME

# Source app helpers
source /usr/share/yunohost/helpers

admin=$(ynh_app_setting_get $app ftp_user)
path=$(ynh_app_setting_get $app path)
domain=$(ynh_app_setting_get $app domain)
appname=$(ynh_app_setting_get $app appname)
sql=$(ynh_app_setting_get $app sql)
final_path=$(ynh_app_setting_get $app final_path)
parent_dir=/var/www/webapp_$admin

# Suppression de la base de données.
# Utilise '$app' comme nom d'utilisateur et de base de donnée
db_user=$app
if [ -n "$db_user" ]
then
	REMOVE_BDD $db_user	# Suppression de la base de donnée et de l'utilisateur associé.
fi

SECURE_REMOVE '$final_path'	# Suppression du dossier de la webapp

app=$appname	# Utilise appname pour FPM et nginx
REMOVE_NGINX_CONF	# Suppression de la configuration nginx

# Vérifie si le dossier parent est vide. Ce qui signifie que toutes les webapp ont été désinstallées. Ainsi que le client ftp net2ftp.
if [ -e "$parent_dir" ]
then
	if test -z "$(ls $parent_dir | head -n1)"
	then
		sudo rmdir $parent_dir
	fi
fi

REMOVE_FPM_CONF	# Suppression de la configuration du pool php-fpm

# Régénère la configuration de SSOwat
sudo yunohost app ssowatconf

echo -e "\e[0m"	# Restore normal color
