#!/bin/bash

ynh_version=$(sudo yunohost -v | grep "moulinette:" | cut -d' ' -f2 | cut -d'.' -f1,2)
if [ $ynh_version = "2.4" ]; then
	webapp=$YNH_APP_INSTANCE_NAME

	# Source app helpers
	. /usr/share/yunohost/helpers
else
	webapp=multi_webapp
	MYSQL_ROOT_PWD_FILE="/etc/yunohost/mysql"
fi
admin=$(sudo yunohost app setting $webapp ftp_user)
path=$(sudo yunohost app setting $webapp path)
domain=$(sudo yunohost app setting $webapp domain)
app=$(sudo yunohost app setting $webapp app)
sql=$(sudo yunohost app setting $webapp sql)
parent_dir=/var/www/webapp_$admin
final_path=$parent_dir$path

# Suppression de la base de données.
# Utilise '$app' comme nom d'utilisateur et de base de donnée
db_user=$app
if [ -n "$db_user" ]
then
	if mysqlshow -u root -p$(sudo cat $MYSQL_ROOT_PWD_FILE) | grep -q "^| $db_user"; then
		echo "Delete db"
		if [ $ynh_version = "2.4" ]; then
			ynh_mysql_drop_db $db_user
			ynh_mysql_drop_user $db_user
		else
			mysql -u root -p$(sudo cat $MYSQL_ROOT_PWD_FILE) -e "DROP DATABASE $db_user ; DROP USER $db_user@localhost ;"
		fi
	fi
fi

# Suppression du dossier de la webapp
if [ -e "$final_path" ]; then	# Delete final_path
	echo "Delete app dir"
	sudo rm -r "$final_path"
fi

# Suppression de la config nginx de la webapp
if [ -e "/etc/nginx/conf.d/$domain.d/$app.conf" ]; then	# Delete nginx config
	echo "Delete nginx config"
	sudo rm "/etc/nginx/conf.d/$domain.d/$app.conf"
	sudo service nginx reload
fi

# Vérifie si le dossier parent est vide. Ce qui signifie que toutes les webapp ont été désinstallées. Ainsi que le client ftp net2ftp.
if [ -e "$parent_dir" ]
then
	if test -z "$(ls $parent_dir | head -n1)"
	then
		sudo rmdir $parent_dir
	fi
fi

# Suppression de la configuration du pool php-fpm
if [ -e "/etc/php5/fpm/pool.d/$app.conf" ]; then	# Delete fpm config
	echo "Delete fpm config"
	sudo rm "/etc/php5/fpm/pool.d/$app.conf"
fi
if [ -e "/etc/php5/fpm/conf.d/20-$app.ini" ]; then	# Delete php config
	echo "Delete php config"
	sudo rm "/etc/php5/fpm/conf.d/20-$app.ini"
fi
sudo service php5-fpm reload

# Régénère la configuration de SSOwat
sudo yunohost app ssowatconf

echo -e "\e[0m"	# Restore normal color
