#!/bin/bash

admin=$(sudo yunohost app setting multi_webapp ftp_user)
path=$(sudo yunohost app setting multi_webapp path)
domain=$(sudo yunohost app setting multi_webapp domain)
app=$(sudo yunohost app setting multi_webapp app)
parent_dir=/var/www/webapp_$admin
final_path=$parent_dir$path

# Suppression du dossier de la webapp
sudo rm -rf $final_path

# Suppression de la config nginx de la webapp
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf

# Vérifie si le dossier parent est vide. Ce qui signifie que toutes les webapp ont été désinstallées. Ainsi que le client ftp net2ftp.
if test -z "$(ls $parent_dir | head -n1)"
then
    sudo rmdir $parent_dir
fi

# Suppression de la configuration du pool php-fpm
sudo rm -f /etc/php5/fpm/pool.d/$app.conf
sudo rm -f /etc/php5/fpm/conf.d/20-$app.ini

# Recharge la configuration Nginx et php5-fpm
sudo service nginx reload
sudo service php5-fpm reload
# Régénère la configuration de SSOwat
sudo yunohost app ssowatconf
