#!/bin/bash

source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script

# Récupère les infos de l'application.
YNH_VERSION	# Récupère le numéro de version de Yunohost.
if [ $ynh_version = "2.4" ]; then
	app=$YNH_APP_INSTANCE_NAME
else
	app=multi_webapp
fi
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
admin=$(sudo yunohost app setting $app ftp_user)
is_public=$(sudo yunohost app setting $app is_public)
final_path=$(sudo yunohost app setting $app final_path)
appname=$(sudo yunohost app setting $app appname)
if test -z "$appname"
then	# Si appname est vide, le nom de l'app est stocké sous l'ancien nom app
	appname=$(sudo yunohost app setting $app app)	# On Récupère l'information.
	sudo yunohost app setting $app app -d	# On supprime l'ancienne information.
	sudo yunohost app setting $app appname -v $appname	# Pour la remplacer par la nouvelle.
fi

CHECK_PATH	# Vérifie et corrige la syntaxe du path.
parent_dir=/var/www/webapp_$user
netftp_path=/ftp_webapp_$user


# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@__PATHTOCHANGE__@$path@g" ../conf/nginx.conf
sed -i "s@__FINALPATH__@$final_path/@g" ../conf/nginx.conf
sed -i "s@__NAMETOCHANGE__@$appname@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$appname.conf

# Make app public if necessary
if [ "$is_public" = "Yes" ];
then
    sudo yunohost app setting $app skipped_uris -v "/"
fi

app=$appname	# Utilise appname pour FPM
POOL_FPM	# Créer le fichier de configuration du pool php-fpm et le configure.

# Recharge la configuration Nginx
sudo service nginx reload
# Régénère la configuration de SSOwat
sudo yunohost app ssowatconf
